version: '3'

services:
  ftp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-alpine
    image: rhene/sftp
    container_name: ftpd
    ports:
      - "2222:22"
    volumes:
      # upload directory
      - ./data/ftp:/home/test/ftp
      # config directory
      # save host key file to /config/sshd/keys
      - ./data/sftp/config:/config/sshd

    environment:
      TZ: Asia/Tokyo
    command: test:pass:1000:1000:ftp
