version: '3'

services:
  ftp:
    restart: always
    # cap_add:
    #   - SYS_ADMIN
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-alpine
    image: rhene/sftp
    container_name: ftpd
    ports:
      - "2222:22"
    volumes:
      # upload directory
      - ./volumes/home/test/ftp:/home/test/ftp
      # config directory
      # save host key file to /config/sshd/keys
      - ./volumes/config/sshd:/config/sshd

    environment:
      TZ: Asia/Tokyo
    command: test:pass:1000:1000:ftp
